/* eslint-disable */

/**
 * Web request model to create a custom report
 */
export type CustomReportCreateWebRequestModel = {
  /**
   * The name of the custom report
   */
  name: string;
  /**
   * The Guc of the dodi this report applies to. This report controls will then work in the context
   * of this dodi. If this is an item level report, it can only be generated by items within that dodi
   */
  appliesTo: string;
};

export namespace CustomReportCreateWebRequestModel {
  /**
   * the discriminator for the model if required for more complex api's
   */
  export const discriminator = 'CustomReportCreateWebRequestModel';
}
