/* eslint-disable */

/**
 * Defines how to update a header that is generated by a data source
 */
export type EditDataSourceHeadersWebRequestModelBase = {
  /**
   * The header Id we want to apply extra settings to
   */
  headerId: string;
  /**
   * Provides a way of overriding the title of a header
   */
  overrideTitle?: string | null;
  discriminator: string;
};

export namespace EditDataSourceHeadersWebRequestModelBase {
  /**
   * the discriminator for the model if required for more complex api's
   */
  export const discriminator = 'EditDataSourceHeadersWebRequestModelBase';
}
